spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cache_penetration?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    
  redis:
    host: 127.0.0.1
